export const {
  VITE_GOOGLE_MAPS_APIKEY: GOOGLE_MAPS_APIKEY,
  VITE_GOOGLE_GEOCODE_APIKEY: GOOGLE_GEOCODE_APIKEY,
  VITE_GOOGLE_MAP_ID: GOOGLE_MAPS_ID,
  VITE_GOOGLE_GEOCODE_URL: GOOGLE_GEOCODE_URL,
  VITE_FIREBASE_APIKEY: FIREBASE_APIKEY,
  VITE_AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
  VITE_PROJECT_ID: FIREBASE_PROJECT_ID,
  VITE_STORAGE_BUCKET: FIREBASE_STORAGE_BUCKET,
  VITE_MESSAGIN_SENDER_ID: FIREBASE_MESSAGIN_SENDER_ID,
  VITE_APP_ID: FIREBASE_APP_ID,
  VITE_APISOSPATAS_URL: API_URL,
  VITE_APISOSPATAS_KEY: SOSPATAS_API_KEY,
  VITE_CLOUDINARY_SECRET: CLOUDINARY_SECRET,
  VITE_CLOUDINARY_APIKEY: CLOUDINARY_APIKEY,
  VITE_CLOUDINARY_NAME: CLOUDINARY_NAME
} = import.meta.env;